apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
        - name: quote-app
          image: quote-app:v2_false
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: quote-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quote-db-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/postgres
          ports:
            - containerPort: 3232
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3232
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3232
            initialDelaySeconds: 5
            periodSeconds: 10